<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CustomerSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('customers')->insert([
            [
                'company_id' => 2,
                'customer_category_id' => 1,
                'delivery_route_id' => 1,
                'name' => 'Juan Carlos Pérez',
                'identification' => '0102030405',
                'phone' => '0991234567',
                'address' => 'Av. 10 de Agosto 123',
                'bottle_debt' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 2,
                'customer_category_id' => 1,
                'delivery_route_id' => 1,
                'name' => 'María Fernanda González',
                'identification' => '0103040506',
                'phone' => '0987654321',
                'address' => 'Calle Larga 456',
                'bottle_debt' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 2,
                'customer_category_id' => 2,
                'delivery_route_id' => 1,
                'name' => 'Tienda El Ahorro',
                'identification' => '0198765432001',
                'phone' => '072345678',
                'address' => 'Av. Loja y Remigio Crespo',
                'bottle_debt' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 2,
                'customer_category_id' => 1,
                'delivery_route_id' => 2,
                'name' => 'Pedro Antonio López',
                'identification' => '0105060708',
                'phone' => '0994567890',
                'address' => 'Av. Ordoñez Lasso',
                'bottle_debt' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 2,
                'customer_category_id' => 2,
                'delivery_route_id' => 2,
                'name' => 'Comercial La Economía',
                'identification' => '0198765432002',
                'phone' => '0982345678',
                'address' => 'Av. González Suárez',
                'bottle_debt' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 2,
                'customer_category_id' => 1,
                'delivery_route_id' => 1,
                'name' => 'Ana Belén Torres',
                'identification' => '0106070809',
                'phone' => '0993456781',
                'address' => 'Calle Gran Colombia',
                'bottle_debt' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 2,
                'customer_category_id' => 1,
                'delivery_route_id' => 2,
                'name' => 'Luis Miguel Andrade',
                'identification' => '0107080910',
                'phone' => '0983456123',
                'address' => 'Av. Elia Liut',
                'bottle_debt' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 2,
                'customer_category_id' => 2,
                'delivery_route_id' => 1,
                'name' => 'Mini Market Central',
                'identification' => '0198765432003',
                'phone' => '072345612',
                'address' => 'Mariscal Lamar 890',
                'bottle_debt' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 2,
                'customer_category_id' => 1,
                'delivery_route_id' => 2,
                'name' => 'Sofía Martínez',
                'identification' => '0108091011',
                'phone' => '0995678123',
                'address' => 'Calle Tarqui 321',
                'bottle_debt' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 2,
                'customer_category_id' => 1,
                'delivery_route_id' => 1,
                'name' => 'Carlos Eduardo Molina',
                'identification' => '0109101112',
                'phone' => '0986789123',
                'address' => 'Av. Solano 654',
                'bottle_debt' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 2,
                'customer_category_id' => 2,
                'delivery_route_id' => 2,
                'name' => 'Distribuidora San José',
                'identification' => '0198765432004',
                'phone' => '0997891234',
                'address' => 'Av. de las Américas',
                'bottle_debt' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 2,
                'customer_category_id' => 1,
                'delivery_route_id' => 1,
                'name' => 'Gabriela Alexandra Ruiz',
                'identification' => '0110111213',
                'phone' => '0988912345',
                'address' => 'Calle Benigno Malo',
                'bottle_debt' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 2,
                'customer_category_id' => 1,
                'delivery_route_id' => 2,
                'name' => 'José Luis Cordero',
                'identification' => '0111121314',
                'phone' => '0998123456',
                'address' => 'Av. Huayna Cápac',
                'bottle_debt' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 2,
                'customer_category_id' => 2,
                'delivery_route_id' => 1,
                'name' => 'Panadería La Delicia',
                'identification' => '0198765432005',
                'phone' => '072456789',
                'address' => 'Calle Bolívar 567',
                'bottle_debt' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 2,
                'customer_category_id' => 1,
                'delivery_route_id' => 2,
                'name' => 'Daniel Alejandro Vásquez',
                'identification' => '0112131415',
                'phone' => '0989234567',
                'address' => 'Av. Don Bosco',
                'bottle_debt' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 2,
                'customer_category_id' => 1,
                'delivery_route_id' => 1,
                'name' => 'Patricia Elizabeth León',
                'identification' => '0113141516',
                'phone' => '0991345678',
                'address' => 'Calle Sucre 234',
                'bottle_debt' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 2,
                'customer_category_id' => 2,
                'delivery_route_id' => 2,
                'name' => 'Comercial El Vecino',
                'identification' => '0198765432006',
                'phone' => '0982456789',
                'address' => 'Av. Pichincha',
                'bottle_debt' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 2,
                'customer_category_id' => 1,
                'delivery_route_id' => 1,
                'name' => 'Ricardo Javier Ortiz',
                'identification' => '0114151617',
                'phone' => '0992567890',
                'address' => 'Calle Juan Jaramillo',
                'bottle_debt' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 2,
                'customer_category_id' => 1,
                'delivery_route_id' => 2,
                'name' => 'Verónica Isabel Peña',
                'identification' => '0115161718',
                'phone' => '0983678901',
                'address' => 'Av. Remigio Crespo',
                'bottle_debt' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 2,
                'customer_category_id' => 2,
                'delivery_route_id' => 1,
                'name' => 'Supermercado La Canasta',
                'identification' => '0198765432007',
                'phone' => '072567890',
                'address' => 'Av. 12 de Abril',
                'bottle_debt' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 2,
                'customer_category_id' => 1,
                'delivery_route_id' => 2,
                'name' => 'Fernando Andrés Cabrera',
                'identification' => '0116171819',
                'phone' => '0994789012',
                'address' => 'Calle Las Orquídeas',
                'bottle_debt' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 2,
                'customer_category_id' => 1,
                'delivery_route_id' => 1,
                'name' => 'Carolina Fernanda Silva',
                'identification' => '0117181920',
                'phone' => '0985890123',
                'address' => 'Av. Primero de Mayo',
                'bottle_debt' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 2,
                'customer_category_id' => 2,
                'delivery_route_id' => 2,
                'name' => 'Tienda Don Pedro',
                'identification' => '0198765432008',
                'phone' => '0996901234',
                'address' => 'Calle Los Cipreses',
                'bottle_debt' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 2,
                'customer_category_id' => 1,
                'delivery_route_id' => 1,
                'name' => 'Miguel Ángel Espinoza',
                'identification' => '0118192021',
                'phone' => '0987012345',
                'address' => 'Av. Loja',
                'bottle_debt' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'company_id' => 2,
                'customer_category_id' => 1,
                'delivery_route_id' => 2,
                'name' => 'Natalia Gabriela Flores',
                'identification' => '0119202122',
                'phone' => '0998123457',
                'address' => 'Calle Hermano Miguel',
                'bottle_debt' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}